### PR TITLE
Fix widget state lag

### PR DESCRIPTION
**Pull request by pavi2410**
- Works smooth as before
- Tested with simple components (checkbox, radio)
- I need to test with other components
- I didn't touch form part yet

### CODE REVIEW

**Comment by franekp** [comment]
Thank you!

I'll merge when it's ready.

**Comment by pavi2410** [comment]
@franekp I fixed everything except multiselect component. You can merge this now.

image

**Comment by pavi2410** [comment]
@franekp Can you please merge this?

**Comment by franekp** [comment]
Closing because the issue has been fixed in streamlit.

**Pull request closed without merging**
